[package]
name = "zed-custom-slack"
version = "0.1.0"
edition.workspace = true
publish.workspace = true
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/zed_custom_slack.rs"
doctest = false

[dependencies]
pulldown-cmark.workspace = true
anyhow.workspace = true
async-tungstenite.workspace = true
collections.workspace = true
futures.workspace = true
gpui.workspace = true
gpui_tokio.workspace = true
log.workspace = true
serde.workspace = true
serde_json.workspace = true
settings.workspace = true
theme.workspace = true
ui.workspace = true
workspace.workspace = true
url.workspace = true
smol.workspace = true
util.workspace = true
editor.workspace = true
menu.workspace = true
collab_ui = { version = "0.1.0", path = "../collab_ui" }
channel = { version = "0.1.0", path = "../channel" }
language = { version = "0.1.0", path = "../language" }
reqwest.workspace = true
tokio-tungstenite = { workspace = true, features = ["rustls-tls-native-roots"] }
